services:
 
  frontend:
    build:
      context: .
      dockerfile: Chatly.Frontend/Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - 4000:80
    depends_on:
      - api
 
  api:
    build:
      context: .
      dockerfile: Services/Messages/Chatly.Messages.Api/Dockerfile
    image: api
    container_name: api
    ports:
      - 8080:8080