services:
 
  frontend:
    build:
      context: .
      dockerfile: Chatly.Frontend/Dockerfile
    image: chatly-frontend
    ports:
      - 4000:80
    depends_on:
      - api
 
  api:
    build:
      context: .
      dockerfile: Services/Messages/Chatly.Messages.Api/Dockerfile
    image: chatly-api
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy  # Wait until health check passes

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: chatly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatly"]
      interval: 5s
      timeout: 5s
      retries: 10